spring:
  application:
    name: InventoryManagement

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${DB_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  flyway:
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    baseline-version: 1
    locations: classpath:db/migration\
    baseline-description: "init"
  messages:
    basename: "messages, config.i18n.messages"
    fallback-to-system-locale: false
jwt:
  secretKey: ${JWT_SECRET_KEY}
server:
  port: 8050
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
